# Generated by Django 5.2.3 on 2025-06-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
