# Generated by Django 5.2.3 on 2025-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0002_remove_student_address_remove_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
