# Generated by Django 5.2.3 on 2025-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0004_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(to='academic_app.course'),
        ),
    ]
