# Generated by Django 5.2.3 on 2025-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0005_remove_batch_course_batch_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(related_name='batches', to='academic_app.course'),
        ),
    ]
