# Generated by Django 5.2.3 on 2025-06-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0009_teacher_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
    ]
