# Generated by Django 5.2.3 on 2025-06-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0011_remove_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_app.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_app.course')),
                ('students', models.ManyToManyField(blank=True, to='academic_app.student')),
                ('subjects', models.ManyToManyField(to='academic_app.subject')),
                ('teachers', models.ManyToManyField(blank=True, to='academic_app.teacher')),
            ],
        ),
    ]
