# Generated by Django 5.2.3 on 2025-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0012_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms', to='academic_app.student'),
        ),
    ]
