# Generated by Django 5.2.3 on 2025-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0013_remove_classroom_teachers_alter_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
    ]
