# Generated by Django 5.2.3 on 2025-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0015_rename_students_classroom_totalstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='totalstudents',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(related_name='classrooms', to='academic_app.subject'),
        ),
    ]
