# Generated by Django 5.2.3 on 2025-06-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0017_remove_timetable_batch_timetable_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='remarks',
        ),
    ]
