# Generated by Django 5.2.3 on 2025-06-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0021_alter_teacherattendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_app.classroom'),
        ),
    ]
