# Generated by Django 5.2.3 on 2025-06-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0022_remove_studentattendance_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='course',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_app.classroom'),
        ),
    ]
